title       = "xtx"
baseURL     = "https://xuetangx-cli.tamnd.com/"
description = "XuetangX MOOC platform CLI"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/xuetangx-cli"
